### PR TITLE
Product Page Added

### PR DESCRIPTION
**Pull request by Mahi24-prog**
### Product listing page where all the products are listed with a section of filters.
**multiple filters on the product listing page including,**

1. Price

2. Category

3. Ratings

### Link For Review
https://ecom-product.netlify.app/pages/product

If Home page is showing then click on shoes1 product page will open.

### CODE REVIEW

**Review by vermasavita — APPROVED** [review]
UI is great. ❤️

**Review by narharikale — APPROVED** [review]
seems good 👍

**Review by harshkotkar5557 — APPROVED** [review]
Looks good to me

**Comment by iamharnad** [comment]
visually looking so good

**Pull request merged**
